### ISSUE TITLE
first high signal not evaluated

### ISSUE THREAD

**Issue by devel0** [GrandFatherADI/PulseStats#1]
- Saleae Logic2 : 2.3.17  ( Commit":"20e49f834efa2f9412d4eb486daf7bd7a0b6d993" )
- PulseStats : 1.1.0

Having follow signals

![image](https://user-images.githubusercontent.com/13405008/106362495-730a6b80-6323-11eb-86b3-91b1cdf3c8b4.png)

with high widths: 
17.063 µs
18 µs
17.188 µs

measurements seems to skip first high signal reporting following stats:

ΔT	1.049494 ms
Nfalling	3 
Nrising	3 
fmin	2.182 kHz
fmax	2.216 kHz
fmean	2.199 kHz
Tstd	5.038 µs
Tavg	454.813 µs
Hmin	17.187 µs
Hmean	17.594 µs
HSDev	574.524 ns
Hmax	18 µs
Lmin	434.188 µs
Lmean	437.281 µs
LSDev	4.375 µs
Lmax	440.375 µs

while Hmin should 17.063 µs and Hmean 17.417 µs

**Comment by GrandFatherADI** [comment]
@devel0 I've pushed a code change that should fix the issue. Can you check it works as expected for me please?

Cheers,
Peter

**Comment by devel0** [comment]
confirmed, it works as expected.
